config/routes.rb
Rails.application.routes.draw do
  root 'jmw#home'
  get '/about_us', to: 'jmw#about_us', as: 'about_us'
  get '/contact_us', to: 'jmw#contact_us', as: 'contact_us'
  get '/our_services', to: 'jmw#our_services', as: 'our_services'


  get 'jmw/index'
  get 'jmw/home'
  get 'jmw/about_us'
  get 'jmw/our_services'
  get 'jmw/web_development'
  get 'jmw/career'
  get 'jmw/contact_us'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/jmw_controller.rb
class JmwController < ApplicationController
  def index
  end

  def home
  end

  def about_us
  end

  def our_services
  end

  def web_development
  end

  def career
  end

  def contact_us
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jmw_helper.rb
module JmwHelper
end

app/views/jmw/about_us.html.erb
<h1>Jmw#about_us</h1>
<p>Find me in app/views/jmw/about_us.html.erb</p>

app/views/jmw/career.html.erb
<h1>Jmw#career</h1>
<p>Find me in app/views/jmw/career.html.erb</p>

app/views/jmw/index.html.erb
<h1>Jmw#index</h1>
<p>Find me in app/views/jmw/index.html.erb</p>

app/views/layouts/_footer.html.erb
<div id="sidebar-footer" class="footer-widgets" role="complementary">
            <div class="container">
               <div class="row">
                  <div class="sidebar-column col-md-3">
                     <section id="text-3" class="widget widget_text">
                        <div class="textwidget">
                           <p><img loading="lazy" class="alignnone size-full wp-image-708" src="http://52.91.135.213/wp-content/uploads/2021/07/Just-Mind-Work.png" alt="" width="200" height="40" /></p>
                        </div>
                     </section>
                  </div>
                  <div class="sidebar-column col-md-3">
                     <section id="text-2" class="widget widget_text">
                        <h3 class="widget-title">Quick Links</h3>
                        <div class="textwidget">
                           <p><%=link_to "home", root_path %></a></p>
                           <p><%=link_to "About", about_us_path %></p>
                           <p><%=link_to "Career", jmw_career_path %></p>
                           <p><%=link_to "Contact", jmw_contact_us_path %></p>
                        </div>
                     </section>
                  </div>
                  <div class="sidebar-column col-md-3">
                     <section id="custom_html-2" class="widget_text widget widget_custom_html">
                        <h3 class="widget-title">Contact Us</h3>
                        <div class="textwidget custom-html-widget">
                           <h3 style="font-size: 22px; color: #595959">
                              +91 81093 37859
                           </h3>
                           admin@justmindwork.com <br/> <br/> 413, Satguru Parinay Opposite C21 Mall, AB Rd, Scheme 54 PU4, Indore, Madhya Pradesh 452011
                        </div>
                     </section>
                  </div>
                  <div class="sidebar-column col-md-3">
                     <section id="athemes_social_widget-1" class="widget widget_athemes_social_widget">
                        <h3 class="widget-title">Let&#8217;s Connect</h3>
                        <div class="menu-social-container">
                           <ul id="menu-social" class="menu social-media-list clearfix">
                              <li id="menu-item-787" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-787"><a href="https://www.linkedin.com/in/justmind-work-368837217/"><span class="screen-reader-text">LinkedIn</span></a></li>
                              <li><i class="fa-brands fa-facebook"></i><a href="https://www.facebook.com/justmindwork"><span class="screen-reader-text">facebook</span></a></li>
                              <li id="menu-item-788" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-788"><a href="https://www.instagram.com/invites/contact/?i=8qa6apvzw67k&#038;utm_content=m8yhss5"><span class="screen-reader-text">Instagram</span></a></li>
                           </ul>
                        </div>
                     </section>
                     <section id="custom_html-1" class="widget_text widget widget_custom_html">
                        <div class="textwidget custom-html-widget">
                           <p style="margin-top:20px">
                              @ Copyright 2021 | Just Mind Work Pvt. Ltd.
                           </p>
                        </div>
                     </section>
                  </div>
               </div>
            </div>
         </div>
         <footer id="colophon" class="site-footer">
            <div class="container">
               <div class="row">
                  <div class="site-info col-md-12">
                     <a href="https://wordpress.org/">Proudly powered by WordPress</a>
                     <span class="sep"> | </span> Theme: <a href="https://athemes.com/theme/airi" rel="nofollow">Airi</a> by aThemes. 
                  </div>
                  <!-- .site-info -->
               </div>
            </div>
         </footer>

app/views/layouts/_header.html.erb
<header>
  <div>
    <div>
      <!-- .site-branding -->
      <div class="">
        <div class="">
          <nav id="" class="navbar">
            <div class="">
              <ul>
                <li><%= link_to image_tag("Just-Mind-Work.png",:size=>'200x40') %></li>
                <li  class="menu_item" style=""><%=link_to "home", root_path %></li>
                <li class="menu_item"><%=link_to "About", about_us_path %></li>
                <li  class="menu_item">
                  <a href="#" class="service menu_item">Our Services</a>
                  <ul class="sub-menu">
                    <li class="">
                      <%= link_to "Web Development", jmw_web_development_path %>
                    </li>
                    <li class="">
                      <%= link_to "Mobile App Solutions", jmw_our_services_path %>
                    </li>
                  </ul>
                </li>
                <li class="menu_item"><%=link_to "Career", jmw_career_path %></li>
                 <li class="menu_item"><%=link_to "Contact", jmw_contact_us_path %></li>
              </ul>
            </div>
          </nav>
          <!-- #site-navigation -->
        </div>
      </div>
    </div>
  </div>
</header>

<style type="text/css">
  ul{
    display: inline-block;
  }
  li {
    display: inline-block;
    margin-left: 30px;
    padding-top: 20px;
  }

  ul>li:hover ul {
    display:block;
  }
  .sub-menu{
    display: none;
  }
  .menu_item{
   margin-left:30px;
  }
  .navbar {
    width: 100%;
    position: fixed;
    background-color: white;
  }
</style>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Jmw</title>
    <%= csrf_meta_tags %>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  </head>

  <body>
    <%= yield %>
  </body>
</html>